baseurl: ""
url: "https://turtlecoin.lol"

# Do not copy these files to the build folder
exclude:
 - Gemfile
 - Gemfile.lock
 - scripts
 - Rakefile
 - README.md
 - .bundle
 - vendor

gems:
 - jekyll-multiple-languages-plugin


# Localization config
languages: ["en", "af", "pt-br", "ru", "zh", "de", "es", "fr", "it"]
# languages: ["en", "af", "pt-br", "ru", "zh", "de", "es", "fr", "it", "dev"] # enable during development to see text keys at /dev/

language_names:
  af:
    short: af
    full: Afrikaans
  zh:
    short: 中文
    full: 中文
  de:
    short: de
    full: Deutsch
  en:
    short: en
    full: English
  es:
    short: es
    full: Español
  fr:
    short: fr
    full: Français
  it:
    short: it
    full: Italiano
  ru:
    short: рус
    full: Русский
  tr:
    short: tr
    full: Turkish
  pt-br:
    short: pt-br
    full: Brazilian Portuguese
  dev:
    short: dev
    full: Development

exclude_from_localizations: ["assets", "js", "images", "css", "fonts", "scripts", "paper-turtle"]
